export default {
  live: {
    meetingTitle: 'Saturno meeting',
    speaking: 'speaking',
    timerSeconds: '32',
    participants: '{{count}} participants',
    chatTitle: 'Room chat',
    chatPlaceholder: 'Type a message (mock)...',
    detailsTitle: 'Meeting details',
    chatTab: 'Chat',
    participantsTab: 'Participants',
    aiSummaryTitle: 'AI summary (coming soon)',
    aiSummaryBody:
      'Here you will see an automatic summary of the main points of the meeting, generated by Saturno AI.',
    hideSidePanel: 'Hide side panel',
    showSidePanel: 'Show side panel',
  },
};

